version: '3'
services:
  elasticsearch:
    image: bitnami/elasticsearch:latest
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ELASTICSEARCH_EXTRA_FLAGS=-Ehttp.max_content_length=500mb
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticnet

  kibana:
    image: bitnami/kibana:latest
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elasticnet

networks:
  elasticnet: