version: '3'
services:
  elasticsearch:
    image: bitnami/elasticsearch:latest
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ELASTICSEARCH_EXTRA_FLAGS=-Ehttp.max_content_length=500mb
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticnet

  kibana:
    image: bitnami/kibana:latest
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elasticnet

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
    - elasticnet

  sonarqube:
    image: sonarqube:latest
    depends_on:
      - postgresql
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - SONAR_JDBC_USERNAME=${POSTGRES_USER}
      - SONAR_JDBC_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - elasticnet

networks:
  elasticnet:

volumes:
  postgresql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
