spring:
  application:
    name: aiassistant
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
openai:
  api:
    key: ${OPEN_AI_API_KEY}

file.upload-dir: ${UPLOAD_DIR}

sonarqube:
  project:
    key: ${SONARQUBE_PROJECT_KEY}
    name: ${SONARQUBE_PROJECT_NAME}
  token: ${SONARQUBE_TOKEN}
  results:
    path: ${SONARQUBE_RESULTS_PATH}
  host:
    url: ${SONARQUBE_HOST_URL}


maven:
  home: C:/Program Files/Apache/apache-maven-3.9.8



